
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class NO2 extends javax.swing.JFrame {
    String menu;
    int harga, Pesanan, Total;
    /**
     * Creates new form NO2
     */
    public NO2() {
        initComponents();
        uPesanan.setText("" + Pesanan);
        btnTambah.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                Pesanan++;
                uPesanan.setText(Integer.toString(Pesanan));
            }
        });
        btnKurang.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                if (Pesanan > 0){
                    Pesanan --;
                    uPesanan.setText(Integer.toString(Pesanan));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bGrup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        uPesanan = new javax.swing.JTextField();
        btnBeli = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPesanan = new javax.swing.JLabel();
        jJumlah = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bRawon = new javax.swing.JRadioButton();
        bNasiUduk = new javax.swing.JRadioButton();
        bNasiGoreng = new javax.swing.JRadioButton();
        bAyamGeprek = new javax.swing.JRadioButton();
        bSateAyam = new javax.swing.JRadioButton();
        bNasiPadang = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 21)); // NOI18N
        jLabel1.setText("\"WELCOME TO  WAROENG AL-BAROKAH\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setText("PILIHAN MENU :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(82, 24, 88, 16);

        jRadioButton1.setText("Ayam Geprek");
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(33, 68, 94, 21);

        jRadioButton2.setText("Soto Daging");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(33, 107, 88, 21);

        jRadioButton3.setText("Nasi Boran");
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(33, 146, 80, 21);

        jRadioButton4.setText("Nasi Goreng");
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(33, 185, 88, 21);

        jRadioButton5.setText("Rawon");
        jPanel2.add(jRadioButton5);
        jRadioButton5.setBounds(145, 68, 59, 21);

        jRadioButton6.setText("Bakso");
        jPanel2.add(jRadioButton6);
        jRadioButton6.setBounds(145, 107, 54, 21);

        jRadioButton7.setText("Rujak Lontong");
        jPanel2.add(jRadioButton7);
        jRadioButton7.setBounds(33, 224, 100, 21);

        jRadioButton8.setText("Nasi Bakar");
        jPanel2.add(jRadioButton8);
        jRadioButton8.setBounds(144, 146, 78, 21);

        jRadioButton9.setText("Sate Ayam");
        jPanel2.add(jRadioButton9);
        jRadioButton9.setBounds(143, 185, 79, 21);

        jRadioButton10.setText("Nasi Uduk");
        jPanel2.add(jRadioButton10);
        jRadioButton10.setBounds(145, 224, 77, 21);

        jPanel3.setLayout(null);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel3.add(btnTambah);
        btnTambah.setBounds(60, 20, 47, 27);

        btnKurang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });
        jPanel3.add(btnKurang);
        btnKurang.setBounds(130, 20, 47, 27);

        uPesanan.setBackground(new java.awt.Color(204, 204, 204));
        uPesanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uPesanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uPesanan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(uPesanan);
        uPesanan.setBounds(50, 60, 130, 55);

        btnBeli.setText("BELI");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        jPanel3.add(btnBeli);
        btnBeli.setBounds(40, 130, 72, 23);

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus);
        btnHapus.setBounds(130, 130, 72, 23);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jPesanan.setText("Pesanan Anda :");

        jJumlah.setText("Jumlah Pesanan :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jJumlah)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(17, 170, 210, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3.jpeg"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 240, 270);

        jPanel5.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("PILIHAN MENU : ");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(80, 60, 120, 20);

        bGrup.add(bRawon);
        bRawon.setText("RAWON");
        jPanel5.add(bRawon);
        bRawon.setBounds(15, 110, 110, 21);

        bGrup.add(bNasiUduk);
        bNasiUduk.setText("NASI UDUK");
        bNasiUduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNasiUdukActionPerformed(evt);
            }
        });
        jPanel5.add(bNasiUduk);
        bNasiUduk.setBounds(15, 149, 110, 21);

        bNasiGoreng.setText("NASI GORENG");
        jPanel5.add(bNasiGoreng);
        bNasiGoreng.setBounds(15, 188, 110, 21);

        bGrup.add(bAyamGeprek);
        bAyamGeprek.setText("AYAM GEPREK");
        jPanel5.add(bAyamGeprek);
        bAyamGeprek.setBounds(144, 110, 110, 21);

        bGrup.add(bSateAyam);
        bSateAyam.setText("SATE AYAM");
        jPanel5.add(bSateAyam);
        bSateAyam.setBounds(144, 149, 110, 21);

        bGrup.add(bNasiPadang);
        bNasiPadang.setText("NASI PADANG");
        jPanel5.add(bNasiPadang);
        bNasiPadang.setBounds(144, 188, 110, 21);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3.jpeg"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, 0, 270, 270);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(250, 0, 280, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
       if (bRawon.isSelected()){
           menu = "RAWON";
           harga = 12000;
       }else if (bNasiUduk.isSelected()){
           menu = "NASI UDUK";
           harga = 11000;
       }else if (bNasiGoreng.isSelected()){
           menu = "NASI GORENG";
           harga = 10000;
       }else if (bAyamGeprek.isSelected()){
           menu = "AYAM GEPREK";
           harga = 14000;
       }else if (bSateAyam.isSelected()){
           menu = "SATE AYAM";
           harga = 10000;
       }else if (bNasiPadang.isSelected()){
           menu = "NASI PADANG";
           harga = 13000;
       }else if (!bRawon.isSelected() && !bNasiUduk.isSelected() && !bNasiGoreng.isSelected() && !bAyamGeprek.isSelected() &&
               !bSateAyam.isSelected()&& !bNasiPadang.isSelected()) {
       JOptionPane.showMessageDialog(this, "Silahkan Pilih Menu!");
       return;
       }
       
       Pesanan = Integer.parseInt(uPesanan.getText());
       Total = Pesanan * harga ;
       jPesanan.setText("Pesanan Anda : " + menu);
       jJumlah.setText("Jumlah Pesanan : " + Pesanan);
       JOptionPane.showMessageDialog(this,
               "Pesanan     : " + menu +
               "\nTotal Harga   : Rp. "+ Total);
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        bGrup.clearSelection();
        uPesanan.setText("");
        jPesanan.setText("Pesanan Anda  : ");
        jJumlah.setText("Jumlah Pesanan : ");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void bNasiUdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNasiUdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNasiUdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NO2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bAyamGeprek;
    private javax.swing.ButtonGroup bGrup;
    private javax.swing.JRadioButton bNasiGoreng;
    private javax.swing.JRadioButton bNasiPadang;
    private javax.swing.JRadioButton bNasiUduk;
    private javax.swing.JRadioButton bRawon;
    private javax.swing.JRadioButton bSateAyam;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jPesanan;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField uPesanan;
    // End of variables declaration//GEN-END:variables
}
